apiVersion: v1
kind: ConfigMap
metadata:
  name: order-ms-config
  namespace: order-ms
data:
  ASPNETCORE_URLS: "http://+:5000"
  ASPNETCORE_ENVIRONMENT: "Development"
  
  # Email
  MAIL: "noreply.soat.fiap@gmail.com"
  DISPLAY_NAME: "FastFoodChallenge"
  HOST: "smtp.gmail.com"
  PORT: "587"