apiVersion: v1
kind: Secret
metadata:
  name: order-ms-secret
  namespace: order-ms
type: Opaque
stringData:
 
    # Esta é a string de conexão para o banco de dados
  DB_CONNECTION_STRING: "mongodb+srv://carloshenrique97_db_user:AH5tjo19c8UMGP0w@fiaptechchallenge4.rqyfkve.mongodb.net/?appName=FiapTechChallenge4"

  # Nome do database
  DB_NAME: "OrderDb"

  # Email
  EMAIL_PASSWORD: sxrs rsip ydzk tuaj

  # Autenticação nas APIs
  API_AUTH_TOKEN: Yf29qN58VfWbT1YtZz7jRkE4sLt9xP2eUqK3LmXvHsDcMgAjBwNvZxQrFtGvKyLz

