apiVersion: v1
kind: Service
metadata:
  name: order-ms-webapi-service
  namespace: order-ms
spec:
  type: LoadBalancer
  selector:
    app: order-ms-webapi
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 5000