apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms-webapi-deployment
  namespace: order-ms
  labels:
    app: order-ms-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-ms-webapi
  template:
    metadata:
      labels:
        app: order-ms-webapi
    spec:
      containers:
      - name: order-ms-webapi
        image: goncalvesc97/fiap-tc-4-order-ms:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Configuração do ambiente de banco de dados 

        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: order-ms-secret
              key: DB_CONNECTION_STRING

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: order-ms-secret
              key: DB_NAME

        # Configuração da chave de autenticação da API

        - name: API_AUTHENTICATION_KEY
          valueFrom:
            secretKeyRef:
              name: order-ms-secret
              key: API_AUTH_TOKEN

        # Configuração do serviço de email
        - name: EMAIL_SETTINGS__MAIL
          valueFrom:
            configMapKeyRef:
              name: order-ms-config
              key: MAIL
        - name: EMAIL_SETTINGS__DISPLAY_NAME
          valueFrom:
            configMapKeyRef:
              name: order-ms-config
              key: DISPLAY_NAME
        - name: EMAIL_SETTINGS__HOST
          valueFrom:
            configMapKeyRef:
              name: order-ms-config
              key: HOST
        - name: EMAIL_SETTINGS__PORT
          valueFrom:
            configMapKeyRef:
              name: order-ms-config
              key: PORT
        - name: EMAIL_SETTINGS__PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-ms-secret
              key: EMAIL_PASSWORD